import { BookingStatus } from './booking'
import { UserRole } from './user'

export const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_ROLE_DENIED_STUDENT: `AUTH_ROLE_DENIED_${UserRole.STUDENT}`,
  AUTH_ROLE_DENIED_COACH: `AUTH_ROLE_DENIED_${UserRole.COACH}`,
  USER_PHONE_EXISTS: 'USER_PHONE_EXISTS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_PROFILE_INVALID: 'USER_PROFILE_INVALID',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_COACH_REQUIRED: `COURSE_COACH_REQUIRED_${UserRole.COACH}`,
  COURSE_COPY_NOT_OWNER: 'COURSE_COPY_NOT_OWNER',
  COURSE_COPY_INVALID_STATUS: 'COURSE_COPY_INVALID_STATUS',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_STATUS_PENDING_LOCKED: `BOOKING_STATUS_${BookingStatus.PENDING}_LOCKED`,
  BOOKING_STATUS_CONFIRMED_LOCKED: `BOOKING_STATUS_${BookingStatus.CONFIRMED}_LOCKED`,
  BOOKING_STATUS_COMPLETED_LOCKED: `BOOKING_STATUS_${BookingStatus.COMPLETED}_LOCKED`,
  BOOKING_STATUS_CANCELLED_LOCKED: `BOOKING_STATUS_${BookingStatus.CANCELLED}_LOCKED`,
  BOOKING_TRANSITION_INVALID: 'BOOKING_TRANSITION_INVALID',
  BODY_METRIC_INVALID: 'BODY_METRIC_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

